version: '3.8'

services:
  #  nginx:
  #    image: nginx:alpine
  #  ports:
  #    - "80:80"
  #    - "443:443"
  #  volumes:
  #    - /etc/letsencrypt:/etc/letsencrypt:ro
  #  depends_on:
  #    - landingpage
  #    - uploader
  #    - weather
  #    - resume
  #    - monitor

  landingpage:
    build: ./landing-page
      #    ports:
      # - "5000:5000"
    expose:
      - 5000

  uploader:
    build: ./file-uploader
    expose:
      - "5003"

  weather:
    build: ./weather-app
    expose:
      - "5002"

  resume:
    build: ./resume-site
    expose:
      - "5001"

  monitor:
    build: ./server-monitor
    expose:
      - "5004"

